#! /bin/bash

[[ $0 != $BASH_SOURCE ]] && export SYMFONY_AUTOSERVE_SETUP="$BASH_SOURCE" || export SYMFONY_AUTOSERVE_SETUP="$0"

export SYMFONY_AUTOSERVE=$(dirname $(readlink -m $SYMFONY_AUTOSERVE_SETUP))
export PATH=$SYMFONY_AUTOSERVE/bin:$PATH
